custom: ["https://github.com/acheong08/ChatGPT/compare", "https://etherscan.io/address/0xF6B12003BfFdB9A9d18a81C70daaBC329Da6A34d"]# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
