---
name: ERROR
about: "DO NOT CLICK THE GREEN BUTTON!!! Click one of the _Open_ buttons below."
title: ''
labels: ''
assignees: ''

---

Are you sure you are not opening a duplicate? From now on, I will not be reading all issues. Use 👍 reaction on an issue to upvote it. I will be reading the top 5 issues each day.
