name: Auto Label Issues

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const issue = context.payload.issue

            // remove All of the labels
            github.rest.issues.removeAllLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
            });

            const labelsToAdd = []
            const labelConditions = [
              {label: 'bug', keywords: ['Bug', 'bug', 'error', 'Error']},
              {label: 'vulnerability', keywords: ['vulnerability', 'Vulnerability', 'leak', 'Leak']},
              {label: 'enhancement', keywords: ['suggestion', 'enhancement', 'feature request', 'Feature request', 'Feature Request']},
              {label: 'documentation', keywords: ['docs', 'documentation', 'Wiki', 'wiki']},
              {label: 'help wanted', keywords: ['help wanted']},
              {label: 'question', keywords: ['question', 'Question', 'Why', 'why', 'How', 'how']},
              {label: 'V1', keywords: ['V1', 'v1']},
              {label: 'V3', keywords: ['V3', 'v3']},
              {label: 'authentication', keywords: ['auth', 'Auth', 'token', 'Token', 'TOKEN', 'config', 'Config', 'CONFIG', 'Unauthorized', '401', '403', '502', '503', 'forbidden', 'Forbidden', 'access', 'block']},
              {label: 'network', keywords: ['openai.com', 'ssl', 'SSL', 'HTTPS', 'Connection', 'connection', 'proxy', 'Proxy', 'PROXY', 'VPN']},
              {label: 'CLI', keywords: ['command program', 'Command Program', 'CLI', 'keybindings', 'Keybindings']},
            ]
            // Add tags based on conditions
            for (const {label, keywords} of labelConditions) {
                for (const keyword of keywords) {
                    if (issue.title.includes(keyword)) {
                        labelsToAdd.push(label)
                        break
                    }
                }
            }

            if (labelsToAdd.length == 0) {
                labelsToAdd.push('triage-needed')
            }

            console.log("All of tags:", labelsToAdd)

            // Add tags
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: labelsToAdd
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
  assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Add assignees
        uses: actions/github-script@v6.4.1
        if: github.event_name == 'issues' && github.event.action == 'opened'
        with:
          script: |
            const assignees = ['acheong08'];
            const assignee = assignees[Math.floor(Math.random() * assignees.length)];
            console.log(`The question will assign to ${assignee}`)

            // Add assignees
            github.rest.issues.addAssignees({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: [assignee]
            })

            // Add comment
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `*Automated*:\n 👋 Thanks for reporting this issue. ${assignee} will review it shortly. In the meantime, please check to see if there are any similar issues already closed.`
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
